name: Super-AV1-Encoder
on: [workflow_dispatch]

jobs:
  encode:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y ffmpeg wget

      - name: Download From Drive
        run: |
          # تأكد من وضع الـ ID الخاص بملفك الـ mkv هنا
          wget --no-check-certificate '16uvPLEoh7qafxS9YxI6mCK0-YlddcDgw' -O input.mkv

      - name: Start AV1 Encoding
        run: |
          # هنا سيقوم السيرفر بتحويل الـ mkv الأصلي إلى mkv مكوّد بـ AV1
          ffmpeg -i input.mkv -c:v libsvtav1 -preset 8 -crf 26 -pix_fmt yuv420p10le -svtav1-params tune=0:film-grain=8 -c:a libopus -b:a 96k output_av1.mkv

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: encoded-video
          path: output_av1.mkv
